//-----------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the C# SDK Code Generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Unity.Services.Ccd.Management.Http;



namespace Unity.Services.Ccd.Management.Models
{
    /// <summary>
    /// InlineObject1 model
    /// </summary>
    [Preserve]
    [DataContract(Name = "inline_object_1")]
    public class InlineObject1
    {
        /// <summary>
        /// Creates an instance of InlineObject1.
        /// </summary>
        /// <param name="file">File content</param>
        [Preserve]
        public InlineObject1(System.IO.Stream file)
        {
            File = file;
        }

        /// <summary>
        /// File content
        /// </summary>
        [Preserve]
        [DataMember(Name = "file", IsRequired = true, EmitDefaultValue = true)]
        public System.IO.Stream File{ get; }
    
    }
}

